#Crie um programa que leia algo pelo teclado e mostre na tela o seu tipo primitivo e todas informações sobre ele

#a = input('Digite algo:')
#print('O tipo primitivo desse valor é', type(a))
#print('Tem espaço?', a.isspace())
#print('É um número?', a.isnumeric())
#print('É alfabético?', a.isalpha())
#print('É alfanumérico?', a.isalnum())
#print('Está em maiúsculo?', a.isupper())
#print('Está em minúsculas?', a.islower())
#print('Está capitalizada?', a.istitle())

#a = input('Digite algo:')
#print('O tipo primitivo desse valor é {}'.format(type(a)))
#print('Tem espaço?{}'.format(a.isspace()))
#print('É um número?{}'.format(a.isnumeric()))
#print('É alfabético?{}'.format(a.isalpha()))
#print('É alfanumérico?{}'.format(a.isalnum()))
#print('Está em maiúsculo?{}'.format(a.isupper()))
#print('Está em minúsculas?{}'.format(a.islower()))
#print('Está capitalizada?{}'.format(a.istitle()))

#Outra forma de usar o .format
print("\033[1;91;46m"+"<->"*15+"\033[0;0m")
a = input("\033[1;91m"+'Digite algo:')
print("\033[1;91;46m"+"<->"*15+"\033[0;0m")
print("\033[1;94m"+f'O tipo primitivo desse valor é {type(a)}')
print("\033[1;94m"+f'Tem espaço?{a.isspace()}')
print("\033[1;94m"+f'É um número?{a.isnumeric()}')
print("\033[1;94m"+f'É alfabético?{a.isalpha()}')
print("\033[1;94m"+f'É alfanumérico?{a.isalnum()}')
print("\033[1;94m"+f'Está em maiúsculo?{a.isupper()}')
print("\033[1;94m"+f'Está em minúsculas?{a.islower()}')
print("\033[1;94m"+f'Está capitalizada?{a.istitle()}')
print("\033[1;91;46m"+"<->"*15+"\033[0;0m")
